feat/landing 1
Nikitabkv/Nikitabkv.github.io pull request #9
Opened 2023-06-09 15:01 UTC by Nikitabkv

2023-06-10 17:03 UTC, TorinAsakura commented
Зачем ты запросил ревью? На что смотреть-то?

2023-06-11 19:10 UTC, Nikitabkv commented
> Зачем ты запросил ревью? На что смотреть-то?

Я тут немного не понимаю как работает с ревью
Правильно понимаю, что когда добавляешь ревьювера, то автоматически запрашивается ревью, когда все проверки проходят? 
Если да, то как поступать правильно, не добавлять ревьюера? 
Или лучше вообще не открывать пр пока задача не выполнена?

2023-06-11 22:02 UTC, TorinAsakura commented
> > Зачем ты запросил ревью? На что смотреть-то?
> 
> Я тут немного не понимаю как работает с ревью Правильно понимаю, что когда добавляешь ревьювера, то автоматически запрашивается ревью, когда все проверки проходят? Если да, то как поступать правильно, не добавлять ревьюера? Или лучше вообще не открывать пр пока задача не выполнена?

1. ПР мы открываем для прозрачности процесса, чтобы можно было отслеживать прогресс
2. При назначении ревьювера - происходит реквест ревью, назначай ревьювера только тогда, когда ПР готов к ревью

2023-06-27 13:52 UTC, Nikitabkv commented
Правильно понимаю, что эта ошибка из-за того, что файл yarn.lock не запушил?
```
YN0028: The lockfile would have been created by this install, which is explicitly forbidden.
```
На всякий случай спрашиваю, т.к. хочу делать коммит, который не решит проблему.

2023-06-27 15:00 UTC, Nikitabkv commented
Вопрос по ошибкам typecheck
Если грешить на путь, то это как-то связанно с ts5 `node_modules/@types/react/ts5.0/index.d.ts`
Но у меня версия 4.9.5

Причем текст ошибок достаточно странный
`
'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 
'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
`
Пытался гуглить, менять зависимости, версии, но ошибка остается, в чем может быть проблема?

2023-06-27 15:07 UTC, Nikitabkv commented
> @Nikitabkv Мы не используем node_modules…

Я знаю, у меня её и нет, я так понимаю это архивы которые лежат в папке `.yarn`
Когда я запускаю `yarn typecheck` полный путь выглядит так:
`../../.yarn/berry/cache/@types-react-npm-18.2.13-f7110efddb-9.zip/node_modules/@types/react/ts5.0/index.d.ts`

2023-06-27 15:08 UTC, TorinAsakura commented
@Nikitabkv это тебе нужно смотреть packageExtension, на сайте ярна, это стандартная ошибка, когда в каком-то пакете чего-то не хватает. Пример того, как пишутся такие патчи ты сможешь найти в файлике .yarnrc.yml

2023-07-03 17:34 UTC, TorinAsakura requested changes
Дальше смотреть не стал

2023-07-03 17:34 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/landing-courses.component.tsx
>            Являясь серым кардиналом, Atlantis имеет влияние на сферу IT и неограниченные возможности
Почему у тебя не используется intl? Хардкодить текста - моветон

2023-07-03 17:34 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/landing-courses.component.tsx
> +        <Text width={['335px', '559px']} fontSize={['increased', 'huge']} lineHeight='140%'>
что такое lineHeight 140%??

2023-07-03 17:34 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/landing-courses.component.tsx
> +      <Layout flexBasis={[20, 195]} alignItems='flex-start'>
ты случаем layout с box не перепутал?

2023-07-03 17:34 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/landing-courses.component.tsx
> +    <Layout flexBasis={[20, 230]} height='100%' />
зачем ты отменяешь ограничения установкой высоты/ширины в 100%? Тебе флексы для чего?

2023-07-03 17:34 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/landing-courses.component.tsx
>        <Divider weight={1} color='#000000' />
почему цвет захардкоден?

2023-07-03 17:42 UTC, Nikitabkv commented on landing/fragments/landing-courses/src/landing-courses.component.tsx
> +        <Text width={['335px', '559px']} fontSize={['increased', 'huge']} lineHeight='140%'>
Отступы между строк текста, по фигме, их надо было как-то иначе делать?

2023-07-05 19:51 UTC, TorinAsakura requested changes

2023-07-05 19:51 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +  <Layout
box для обёртки, layout для строительства

2023-07-05 19:51 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +    <Column overflowX='hidden'>
а зачем ты скролл скрыл?

2023-07-05 19:51 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +          defaultMessage='Вы изучите фундаментальные знания в ИТ и прокачаетесь в направлении программирования.
defaultMessage есть смысл указывать, когда языков несколько

2023-07-05 19:51 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +          id='YouStudyDesktop1'
ID должны быть репрезентативны, ни я ни ты не сможем догадаться через пару дней, какой контекст у твоего месседже по его ID, а должны бы

2023-07-05 19:51 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +      <Text width='694px' fontSize='increased' lineHeight='140%' display={['none', 'inline-flex']}>
Нарушена семантика: текста не могут быть без контейнеров

2023-07-05 19:52 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/landing-courses.component.tsx
> +        <Text width={['335px', '559px']} fontSize={['increased', 'huge']} lineHeight='140%'>
все размеры, токены, отступы, цвета, задаются в теме, никаких "ручных" внесений

2023-07-05 21:15 UTC, Nikitabkv commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +    <Column overflowX='hidden'>
> а зачем ты скролл скрыл?

Этот скролл вышел немного не так, как планировался, решил мелкие баги исправить, когда все остальные фрагменты переделаю в целом правильно, буду детально по фигме перепроверять всё перед запросом ревью
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/108034376/85b1b860-d294-40df-8e95-96b6c9667158)

2023-07-06 23:47 UTC, TorinAsakura requested changes
Дальше даже смотреть не стал, вся разметка в пустых дивах и каких-то врапперах

2023-07-06 23:47 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/locale/messages.ts
> +  [LOCALES.RU]: {
что это и откуда взялся апперкейс?

2023-07-06 23:47 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/locale/locales.ts
> +const LOCALES = {
ты на стэк оверфлоу чтоли смотрел?

2023-07-06 23:47 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/locale/messages.ts
> +    FirstParagraphSecondThirdAboutMobile: 'за свои решения по прежднему мало. ',
А если их будет десять?

2023-07-06 23:47 UTC, TorinAsakura commented on landing/fragments/landing-about/src/landing-about.component.tsx
> +    <Box flexBasis={[0, 230]} />
почему бокс на месте лэйаута?

2023-07-06 23:47 UTC, TorinAsakura commented on landing/fragments/landing-about/src/landing-about.component.tsx
> +          <Box>
зачем пустой бокс?

2023-07-07 00:29 UTC, Nikitabkv commented on landing/entrypoints/renderer/src/locale/messages.ts
> +    FirstParagraphSecondThirdAboutMobile: 'за свои решения по прежднему мало. ',
> А если их будет десять?

Исправил мобильные с помощью white-space и \n

2023-07-07 01:03 UTC, Nikitabkv commented
> Дальше даже смотреть не стал, вся разметка в пустых дивах и каких-то врапперах

Не совсем понял про пустые дивы, если речь о том, что я использовал box, вместо layout, то я поменяю обратно, видимо я не правильно понял сообщение:

> ты случаем layout с box не перепутал?

Про враперы правильно ли я понял, что не надо было оборачивать вот так:
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/108034376/17465841-a535-4d3b-b70b-b49d56dd9e21)
А сделать так: 
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/108034376/d40ed1c4-1e23-4bef-affd-d410281fc862)

2023-07-07 16:25 UTC, TorinAsakura commented
> > Дальше даже смотреть не стал, вся разметка в пустых дивах и каких-то врапперах
> 
> Не совсем понял про пустые дивы, если речь о том, что я использовал box, вместо layout, то я поменяю обратно, видимо я не правильно понял сообщение:
> 
> > ты случаем layout с box не перепутал?
> 
> Про враперы правильно ли я понял, что не надо было оборачивать вот так: ![image](https://user-images.githubusercontent.com/108034376/251608698-17465841-a535-4d3b-b70b-b49d56dd9e21.png) А сделать так: ![image](https://user-images.githubusercontent.com/108034376/251608632-d40ed1c4-1e23-4bef-affd-d410281fc862.png)

ты вообще понимаешь что происходит?
у тебя div живёт в span, тебя тут вообще ничего не смущает? Серьёзно?

2023-07-10 13:39 UTC, TorinAsakura requested changes

2023-07-10 13:39 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/messages/messages.ts
> +    FaqQuestion1: 'Подойдёт ли мне профессия?',
Зачем ты дублируешь одинаковый контент? Ты же его рендеришь в цикле…

2023-07-10 13:39 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/messages/messages.ts
> +    TechnologiesFirstList: 'JAVASCRIPT — HTML — CSS — SASS — VANILLA JS — JADE — JAVASCRIPT — HTML',
Не-а, не прокатит, смотри как сделано у твоих соседей по курсу

2023-07-10 13:39 UTC, TorinAsakura commented on landing/fragments/landing-creation-process/src/landing-creation-process.component.tsx
> +      </Row>
битая семантика:
- есть направляющие (роу, колумн)
- есть стилизатор (бокс)
- есть разметка через layout

Все элементы должны иметь свои контейнеры для управления их позиционированием. Позиционирование элементов как самостоятельных объектов в контексте DOM - моветон

2023-07-10 14:16 UTC, Nikitabkv commented on landing/fragments/landing-creation-process/package.json
> +  "name": "@landing/creation-process-fragment",
> что такое creation-proccess?

Данный блок, или лучше его просто слайдер назвать?
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/108034376/ef71ce81-d1ed-4cca-afe5-440b10e85e95)

2023-07-10 23:33 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/messages/messages.ts
> +    FaqQuestion1: 'Подойдёт ли мне профессия?',
Это излишне

2023-07-10 23:33 UTC, TorinAsakura commented on landing/fragments/landing-creation-process/package.json
> +  "name": "@landing/creation-process-fragment",
Это слайдер…

2023-07-11 13:49 UTC, TorinAsakura requested changes

2023-07-11 13:49 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/locale/messages.ts
> +    FirstParagraphSecondThirdAboutMobile: 'за свои решения по прежднему мало. ',
не понял о чём ты, но, я тебя спросил: "а что если элементов будет 10?", что будешь каждого именновать через литеральный список?) 1,2,3,4,5,н+1?)

2023-07-11 13:49 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/pages/_app.tsx
> +  <IntlProvider messages={MESSAGES[LOCALES.RU]} locale={LOCALES.RU} defaultLocale={LOCALES.RU}>
смотри как делаем мы в наших репах и не делай так больше

2023-07-11 14:10 UTC, Nikitabkv commented on landing/entrypoints/renderer/src/pages/_app.tsx
> +  <IntlProvider messages={MESSAGES[LOCALES.RU]} locale={LOCALES.RU} defaultLocale={LOCALES.RU}>
> не понял о чём ты, но, я тебя спросил: "а что если элементов будет 10?", что будешь каждого именновать через литеральный список?) 1,2,3,4,5,н+1?)

Всё, понял, вопрос к наименованиям, поправлю 
Я подумал речь о том, что у меня на мобильной было так же как и на десктопе много сообщений, при том, что на мобильной можно было просто сделать переносы (текст не вставал так же, как в фигме, что бы я не делал, при абсолютно идентичных размерах всего)

> смотри как делаем мы в наших репах и не делай так больше

Постараюсь, просто не смог найти пример по react-intl
А что можно было заглянуть в eshevlyakova.github.io, только пока писал это додумался

2023-07-11 14:51 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/pages/_app.tsx
> +  <IntlProvider messages={MESSAGES[LOCALES.RU]} locale={LOCALES.RU} defaultLocale={LOCALES.RU}>
> смотри как делаем мы в наших репах и не делай так больше

github.com/torin-asakura/misik да и в этой же организации другие исходники сайтов лежат, примеров - море

2023-07-13 13:53 UTC, TorinAsakura requested changes

2023-07-13 13:53 UTC, TorinAsakura commented on landing/entrypoints/renderer/locales/ru.json
> +{
Пожалуйста, используй общепринятую стилизацию кода

2023-07-14 07:27 UTC, Nikitabkv commented
> Пожалуйста, используй общепринятую стилизацию кода

По чату обсудили что сообщения оставляю как есть

Нужно ли мне делать новый ревью реквест или проверяется этот ещё?
(Если новый, то я думаю ещё пару раз пересмотреть всё у себя ближе к вечеру и отправить новый запрос ночью) 

Спрашиваю, что бы правильно заполнить дсм, пока не уехал

2023-07-14 08:54 UTC, TorinAsakura commented
@Nikitabkv Нужно

2023-07-14 16:40 UTC, TorinAsakura commented on .gitignore
> +/landing/entrypoints/renderer/src/.next/
можно просто .next
посмотри как в других репах сделано, а можешь вообще оттуда взять гитигнор, он везде одинаковый у нас

2023-07-14 16:44 UTC, TorinAsakura requested changes
Дальше даже смотреть не стал

2023-07-14 16:44 UTC, TorinAsakura commented on landing/fragments/landing-about/src/landing-about.component.tsx
> +      <Column display={['none', 'flex']}>
как сейчас выглядит у тебя структура с точки зрения DOM
div>div>span | span | unicode | svg | span | span | unicode | svg - просто бесхозная куча портяночных строк, которыми нельзя управлять в потоке, так как нет родительских контейнеров, почитай правила семантической вёрстки

2023-07-14 16:44 UTC, TorinAsakura commented on landing/fragments/landing-about/src/landing-about.component.tsx
> +        <br />
это что за жесть?

2023-07-14 17:54 UTC, Nikitabkv commented on landing/fragments/landing-about/src/landing-about.component.tsx
> +      <Column display={['none', 'flex']}>
> как сейчас выглядит у тебя структура с точки зрения DOM div>div>span | span | unicode | svg | span | span | unicode | svg - просто бесхозная куча портяночных строк, которыми нельзя управлять в потоке, так как нет родительских контейнеров, почитай правила семантической вёрстки

сейчас как раз это исправляю

2023-07-18 17:50 UTC, TorinAsakura requested changes
Мой личный рейтинг по Шкале Хаоса 9/10

2023-07-18 17:50 UTC, TorinAsakura commented on landing/fragments/landing-about/src/landing-about.component.tsx
>          <Row flexWrap='wrap' alignItems='center'>
прверь семантику и вложенность на предмет лишнего

2023-07-18 17:50 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +          <Text fontSize='increased' lineHeight='high' display={['none', 'inline-flex']}>
Зачем тебе inline-flex понадобился?

2023-07-18 17:50 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +        <Box width={['228px', '496px']}>
а этот тут зачем? ничего не понимаю

2023-07-18 17:50 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
>      <Column
зачем ты взял column чтобы потом сделать из него row?

2023-07-19 13:22 UTC, Nikitabkv commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
>      <Column
> зачем ты взял column чтобы потом сделать из него row?

Потому что row имеет width='100%' и это не будет работать правильно, а flexGrow расширяет блок до максимума в данном случае, если делать через row, тогда и у соседних блоков придется указывать width, вместо flexBasis

2023-07-19 13:23 UTC, Nikitabkv commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +        <Box width={['228px', '496px']}>
> а этот тут зачем? ничего не понимаю

Если речь про размеры на 60 строке, то это просто для соответствия макету

2023-07-19 13:24 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
>      <Column
Я спрашивал не про flexGrow

2023-07-20 22:35 UTC, TorinAsakura requested changes
Я настоятельно тебе рекомендую поближе и подольше поразбираться с тем, как работает флексбокс. Пока тут нечего проверять.

2023-07-20 22:35 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/landing-faq.component.tsx
> +        height={['549px', 'auto']}
а я думал мы выставляем значения через флекс пропсы типа basis…окей, а что будет если высота объектов внутри будет больше того, что ты поставил?

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-hero/src/landing-hero.component.tsx
> +  <Box color='white' background='gray' justifyContent={['center', 'flex-start']}>
цвет из темы

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-hero/src/landing-hero.component.tsx
> +        </Box>
лучше задавать `display` боксу-обертке, а не тексту

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-hero/src/landing-hero.component.tsx
> +        >
колонне не стоит задавать флекс дирекшн, т.к. из названия колонна уже понятно направление главной оси

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-process/src/landing-process.component.tsx
> +]
нужен ли здесь такой хардкод?

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-process/src/landing-process.component.tsx
> +  <Box background='gray' justifyContent={['center', 'center']} id='process'>
цвета из темы

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-process/src/landing-process.component.tsx
> +          </Box>
Если есть `position='absolute'`, советуют указывать `position='relative` у блока, относительно которого позиционируются

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-process/src/list-item/list-item.component.tsx
> +    <Box className='row' flexDirection={['column', 'row']} color='white'>
опять `className`

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-process/src/list-item/list-item.component.tsx
> +    {isLastItem ? '' : <Layout flexBasis={[28, 48]} />}
не понимаю конструкцию. у тебя либо пустая строка, либо разметка показывается?
если и делать так, то может одним тернарником отрисовывать одну колонну с лейаутами и дивайдером?

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-runline/src/line/line.component.tsx
> +        <Text fontSize={['hugePlus', 'largest']} color='white' whiteSpace='nowrap'>
цвета из темы

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-runline/src/technology/technology.component.tsx
> +]
я на данном этапе задал воркспейсы не дублируя, т.к. понятно что на следующих этапах эти линии будут зацикленны.

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-runline/src/line/line.component.tsx
> +  </Box>
а где тире между йатемами?

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-slider/src/landing-slider.component.tsx
> +  <Box background='gray' color='white'>
цвета из темы

2023-07-25 10:38 UTC, Mirved64 commented on landing/fragments/landing-slider/src/landing-slider.component.tsx
> +      </Box>
из-за того, что ты поставил /n в тексте меседжа, тебе приходится делать дополнительный блок для мобилки. Может лучше настроить размеры блока?

2023-07-25 10:38 UTC, Mirved64 commented on landing/pages/index-page/src/index.page.tsx
> +    <LandingFaq />
нужен ли `Landing` в названиях помпоненто?

2023-07-25 10:47 UTC, TorinAsakura requested changes

2023-07-25 10:47 UTC, TorinAsakura commented on landing/entrypoints/renderer/locales/ru.json
> +  "landing_hero_mobile.slogan": "Мы не учим программированию и дизайну, \nмы учим мышлению, способному реализовывывать \nневозможные идеи.",
Если оно работает и не ломать контроль - то почему нет?

2023-07-25 10:47 UTC, TorinAsakura commented on landing/fragments/landing-header/src/landing-header.component.tsx
> +    <Column width='100%'>
Он всё правильно сделал. Сам подумай, за ким хером тогда нужна колонна или строка, если, по твоему представлению можно всё захерачить через бокс?) Это называется "руллерами" - направляющими, бокс тут задаёт декорацию, а колонна направление потока

2023-07-25 10:47 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/landing-hero.component.tsx
> +        >
ну, он тут делает адаптивную часть, другой вопрос, зачем это делать в направляющем

2023-07-25 10:47 UTC, TorinAsakura commented on landing/fragments/landing-process/src/landing-process.component.tsx
> +]
однозначно нет

2023-07-25 10:47 UTC, TorinAsakura commented on landing/pages/index-page/src/index.page.tsx
> +    <LandingFaq />
Это нормальный подход, ну вот представь, у тебя будет 4 воркйспеса, 4 приложения, и у всех будет Header, Hero, и тебе надо в проекте пойти и найти Hero для лендинга. Как думаешь, что ты по запросу <Hero> увидишь в поисковой выдаче в проекте? Верно, ты увидишь ВСЕ фрагменты, так как они не именованы

2023-07-25 12:06 UTC, oksssvv requested changes

2023-07-25 12:06 UTC, oksssvv commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +        <Box background='grey' flexBasis={['64px', '240px']} justifyContent='center' order={[1, 0]}>
где то `grey`, где то `gray` ))
в будущем будут использоваться не 2 цвета, а десятки, и придется все таки не дефолтные цвета css выставлять
так что прописывай путь цвету который ты задал у тебя в теме - `background='background.gray'`

2023-07-25 12:06 UTC, oksssvv commented on ui/theme/src/theme/colors.ts
> +  second: 'rgba(0, 0, 0, 1)',
ни разу не увидела `second` за всю верстку, чего он тут тогда делает, посмотри в наших репах, как оформляются цвета и впоследствии используются, а если не понятно - то обратись за помощью

2023-07-25 12:06 UTC, oksssvv commented on ui/theme/src/theme/fonts.ts
> +  second: 'GellaDisplay',
ты добавил фонт, но почему то в runline его не использовал

2023-07-25 12:33 UTC, oksssvv commented on landing/fragments/landing-courses/src/about-courses/about-courses.component.tsx
> +        <Box background='grey' flexBasis={['64px', '240px']} justifyContent='center' order={[1, 0]}>
@Nikitabkv 
стоп машина, у тебя тут все нормально, за исключением что `grey` все таки нет в твоей теме

2023-07-26 10:29 UTC, Nikitabkv commented on landing/fragments/landing-about/src/landing-about.component.tsx
> +        <Box flexBasis={76} justifyContent='center'>
Родитель общий, центрируется и текст
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/108034376/f662d364-be3a-4808-a9eb-ba43c3e7c8f0)

2023-07-26 10:32 UTC, Nikitabkv commented on landing/fragments/landing-slider/src/landing-slider.component.tsx
> +      <Box
> а что это за бокс?
Заглушка для слайдера, он же не на первом этапе делается

2023-07-26 14:21 UTC, Mirved64 requested changes
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/99605124/aaf1c4e4-b6ba-4402-9f8d-4571748c865a)
Должна быть меньше и по центру блока

![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/99605124/a835d651-2262-490d-8b50-2e80c7e3de58)
Блоки про библиотеки и дизайн, фигма, математика не так расположены, расстояние не то.

![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/99605124/2088f857-0cc6-4dd2-a5f5-af03065f8bbe)
В макете по другому

2023-07-26 14:21 UTC, Mirved64 commented on landing/fragments/landing-courses/src/landing-courses.component.tsx
> +  <Box background='white' justifyContent={['center', 'normal']} id='courses'>
Вопрос! Стоит ли название параметра цвета привязывать к цвету, а не к месту его применения? Вот в третьем степе будем задавать цвета, и цвет `wait` или `gray` будут с другими параметрами `rgba`, т.е нужно менять в теме название, и во всех местах применения. Не лучше ли назвать абстракцией, привязанной к контексту?

2023-07-27 02:45 UTC, oksssvv requested changes

2023-07-27 02:45 UTC, oksssvv commented on landing/entrypoints/renderer/locales/ru.json
> +  "landing_hero.slogan": "Мы не учим программированию и дизайну, мы учим мышлению, \nспособному реализовывывать невозможные идеи.",
для осуществления переноса текста используется ширина родительского блока

(если у тебя, например, будет текстовая колонка в 3000 слов, ты по такому же принципу будешь выставлять переносы?)

2023-07-27 02:45 UTC, oksssvv commented on landing/fragments/landing-about/src/landing-about.component.tsx
> +    <Column flexBasis={[335, 1460]} flexGrow={1} flexShrink={0}>
этот фрагмент успешно провалил проверку на адаптивность под меньший вьюпорт, т.к.  контейнеру  указан запрет на сжатие

![Снимок экрана от 2023-07-27 05-08-58](https://github.com/atls-academy/Nikitabkv.github.io/assets/126156026/037ed9ec-6c0e-4ed9-835d-1eb8e4632a8b)

2023-07-27 02:45 UTC, oksssvv commented on ui/theme/src/theme/colors.ts
> +  background: {
зочем?

назвал цвета по месту их использования, не проще ли по назвать цвет в соответствии с цветом?)

будет у тебя 60 разных мест использования обычного белого цвета, выстроишь колонну из одинаковых цветовых значений `rgba(255, 255, 255, 1)`  но с разными ключами?

хотя ты почти это и сделал) по итогу в использовании 2 цвета, а сделано 9, как так

2023-07-27 05:23 UTC, Mirved64 commented on ui/theme/src/theme/colors.ts
> +  background: {
> зочем?
> 
> назвал цвета по месту их использования, не проще ли по назвать цвет в соответствии с цветом?)
> 
> будет у тебя 60 разных мест использования обычного белого цвета, выстроишь колонну из одинаковых цветовых значений `rgba(255, 255, 255, 1)` но с разными ключами?
> 
> хотя ты почти это и сделал) по итогу в использовании 2 цвета, а сделано 9, как так

@oksssvv 
а если цвет в макете изменится? так будет в 3 степе. Придется все цвета переименновывать в теме, и местах применения. Ведь не будет под ключом `gray` лежать цвет `rgba(77, 60, 242, 1)`

2023-07-27 07:22 UTC, Mirved64 requested changes
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/99605124/841f0c70-0f08-4592-aea3-e9cc870c66f3)
в макете
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/99605124/c3251db6-4286-4e20-bfb1-e18b7ce8b089)
у тебя. Может эти элементы должны быть в отдельном блоке, который займет всю ширину, и не будет зазора справа?

![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/99605124/dd115943-b7b8-463b-8b0f-a8a1d7989032)
Заглушка сломалась. Тут изображение, а не иконка нужна. и в слайдере нужно изображение, а не черный див.

![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/99605124/14affdcf-ca39-469c-a25e-55845dd13605)
у тебя
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/99605124/c0485db1-6f17-4eab-8e15-c988bc9ab9f6)
в макете. 
@TorinAsakura тут дефолтный шрифт `Helvetica` цифры отображает не так как в макете. Я ставил сторонний шрифт `Helvetica` и цифры стали как в макете, но текст поехал.

2023-07-27 13:52 UTC, Nikitabkv commented
> для осуществления переноса текста используется ширина родительского блока (если у тебя, например, будет текстовая колонка в 3000 слов, ты по такому же принципу будешь выставлять переносы?)

Колонка в 3000 слов это все же не один-два переноса для красоты в каком-нибудь слогане, а полноценная статья, зачем усложнять? Да и Андрей, вроде, сказал: 'если работает, то почему бы и нет'

> @TorinAsakura тут дефолтный шрифт `Helvetica` цифры отображает не так как в макете. Я ставил сторонний шрифт `Helvetica` и цифры стали как в макете, но текст поехал.

По-моему разница только в цифре 1, но факт есть факт

@TorinAsakura, помоги разрешить вопрос с переносами, а так же что делать со шрифтом, действительно не как на макете цифра 1 (при не очень пристальном сравнении с макетом, отличий других символов не нашел)

2023-07-27 17:56 UTC, oksssvv commented on ui/theme/src/theme/colors.ts
> +  background: {
@Mirved64 
ничего тяжелого не вижу в том что бы добавить нужный цвет, затем изменить значение свойства бг в компоненте
а вот копипаста в виде 7и одинаковых значений для разных ключей - меня смутила все таки

![Снимок экрана от 2023-07-27 20-46-06](https://github.com/atls-academy/Nikitabkv.github.io/assets/126156026/8ae4274a-d571-4a0e-8cd3-796d24057cb7)

>а если цвет в макете изменится? так будет в 3 степе. Придется все цвета переименновывать в теме, и местах применения.

у меня на данном этапе например бг секций завершен, я не лазила, не меняла и не переименовывала цвета.
действия были такие:
- добавление нового цвета, его название отражает цвет который указывается  
напр. `purple`: `rgba(77, 60, 242, 1)`
- дальнейшее добавление в компонентах и переиспользование где нужно и  когда это требуется
и никакой копипасты

ИЛИ  ты добавляешь цвет с привязкой к одной секции, к примеру `faq-fragment`, в дальнейшем этот цвет тебе понадобится еще в 20 местах в проекте, если это например фиолетовый, коего будет много по макету, и ты будешь эти 20 одинаковых rgba добавлять в тему? а зочем?)

2023-07-28 09:43 UTC, Mirved64 commented on ui/theme/src/theme/colors.ts
> +  background: {
@oksssvv 

Просто когда изучал CSS, был дан совет не называть параметры цвета именами цветов, т.к. если придут правки по цветам в макете, достаточно изменить параметр цвета и в нужных местах он поменяется. А если был один цвет, стал другой то придется менять название ключа к параметру, менять значение в местах применения. Копипаста на первом этапе это необходимое зло.

2023-07-28 10:04 UTC, Mirved64 requested changes
в целом  норм, но
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/99605124/80860fbe-0398-48c6-9513-7d6d79679659)

2023-07-28 13:04 UTC, Nikitabkv commented
> в целом норм, но ![image](https://user-images.githubusercontent.com/99605124/256790874-80860fbe-0398-48c6-9513-7d6d79679659.png)

По поводу отступа я смотрел у @oksssvv, у неё тоже этот отступ есть и, вроде, ничего не говорили

Просто если делать отдельный блок, то придется добавлять лишние блоки, есть ли в этом большой смысл, нужен комментарий @TorinAsakura или @oksssvv, если это уже обсуждали

2023-07-29 05:08 UTC, Mirved64 approved these changes
в нескольких местах я бы по другому верстал, но в целом  годится

2023-07-30 16:45 UTC, oksssvv requested changes
совет: проверяй надобность свойств после завершения верстки компонента

2023-07-30 16:45 UTC, oksssvv commented on landing/fragments/landing-hero/src/landing-hero.component.tsx
> +          <Box flexBasis={[104, 56]} flexShrink={0} justifyContent='center' alignItems='center'>
не понимаю зачем лишнее указание флексШринков и флексГроу, у меня по сей момент всё хорошо функционирует без этого

![Снимок экрана от 2023-07-30 19-04-02](https://github.com/atls-academy/Nikitabkv.github.io/assets/126156026/2e1f7b14-c70b-421a-90c3-207d749908ff)

- я понимаю что это неопытность, но когда заканчиваешь верстку компонента проходись и проверяй а точно ли тебе нужны все выставленные свойства, чтоб потом ревьюеры не ходили и не собирали их по проекту

2023-07-30 16:45 UTC, oksssvv commented on ui/link/src/link.styles.ts
> +export const activeLinkStyles: styleFn = (active) => active && { color: 'red' }
где применяется активная ссылка?

сейчас посмотрела, а у меня тоже эта дичь есть, не повторяй моих ошибок)

на самом деле до 6го этапа у меня обычная ссылка ни разу не использована, онли `NextLink`

2023-07-31 11:35 UTC, Nikitabkv commented
@oksssvv 
> не понимаю зачем лишнее указание флексШринков и флексГроу, у меня по сей момент всё хорошо функционирует без этого
> 
> ![Снимок экрана от 2023-07-30 19-04-02](https://user-images.githubusercontent.com/126156026/257062254-2e1f7b14-c70b-421a-90c3-207d749908ff.png)
> 
> * я понимаю что это неопытность, но когда заканчиваешь верстку компонента проходись и проверяй а точно ли тебе нужны все выставленные свойства, чтоб потом ревьюеры не ходили и не собирали их по проекту

Тут дело в том, что у тебя на мобилке фикс ширина, что на 370, что на 600, убрать эти гроу и шринки и у меня просто иконки прилипнут к левой стороне

> указание высоты - лишнее телодвижение

Колумн же по умолчанию height='100%', если я уберу ограничение, то получиться каша с лэйаутами у которых flexBasis указан, надо будет либо с ними делать что-то, либо обертки делать дополнительные

2023-07-31 23:44 UTC, Nikitabkv commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +    <Layout flexBasis={16} display={['flex', 'none']} />
Не совсем понимаю, почему нет? Карточки отдельные, обернутые блоком

2023-08-01 05:21 UTC, oksssvv commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +    <Layout flexBasis={16} display={['flex', 'none']} />
> Не совсем понимаю, почему нет? Карточки отдельные, обернутые блоком

На скрине видно что есть 2 отдельных элемента, у каждого свой личный отступ слева, а не общий

2023-08-01 11:06 UTC, Nikitabkv commented
@TorinAsakura 
Можешь подсказать как воспроизвести ошибку которую мне проверки тут выдали у себя?
У меня все скрипты в packag'ах работают, погрешил на `yarn install`, но я зависимости не менял никакие

Или это просто ошибка сети при проверке? Её можно перезапустить? 

**Checks / Release**
`
Http Error: invalid json response body at https://api.github.com/repos/atls-academy/Nikitabkv.github.io/check-runs reason: Unexpected end of JSON input
`

2023-08-03 13:48 UTC, merged